spring.application.name=my-portfolio-backend
spring.datasource.url=jdbc:postgresql://ep-lingering-field-acqgeei3-pooler.sa-east-1.aws.neon.tech/portfolio?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_k9y2LpSaXGlV
spring.datasource.hikari.maximun-pool-size= 10
spring.datasource.hikari.connection-timeout= 20000

spring.sql.init.mode=always



